authentication/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('login', views.signin, name="sign-in"),
    path('sign-up', views.signup, name="sign-up"),
    path('sign-out', views.signout, name="sign-out"),


    
]

food_recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('foods.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foods/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import UserRecipesListView, RecipesListView, home, RecipesDetailView, RecipesCreateView, RecipeUpdateView, RecipeDeleteView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('recipes', RecipesListView.as_view(), name="recipes"),
    path('recipes/<int:pk>', RecipesDetailView.as_view(), name="recipes-detail"),
    path('my-recipes', UserRecipesListView.as_view(), name="my-recipes"),
    path('create-recipe', RecipesCreateView.as_view(), name="create-recipe"),
    path('my-recipes/edit/<int:pk>', RecipeUpdateView.as_view(), name="recipes-edit"),
    path('my-recipes/delete/<int:pk>', RecipeDeleteView.as_view(), name="recipes-delete"),



]
 

authentication/models.py
from django.db import models

# Create your models here.

foods/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

from PIL import Image
# Create your models here.


class Recipe(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=30, null=True,
                             blank=False, verbose_name='Recipe Name')
    pic_file = models.ImageField(
        default='default.jpg', verbose_name="Choose a picture", upload_to='recipe_pictures')
    description = models.TextField(verbose_name="How to prepare!")
    ingredients = models.TextField(verbose_name="Ingredients required")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created', 'title']

    def __str__(self):
        return self.title

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #     if self.pic_file:
    #         image = Image.open(self.pic_file.path)

    #         if image.width > 500:
    #             width, height = image.width, image.height
    #             output_size = (500, 500*(height/width))
    #             image.thumbnail(output_size)

    #             image.save(self.pic_file.path)

foods/forms.py
from statistics import mode
from django import forms
from django.forms import ModelForm
from .models import Recipe

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'pic_file', 'description', 'ingredients']

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
import re
# Create your views here.

# regex for password validation
PASS_REGEX = r"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{8,35}$"


def signup(request):
    signup_context = {'passError': False, 'emailExist': False,
                      'currEmail': '', 'currFname': '', 'currLname': '', 'passErrorMessage': 'Password Error'}

    if request.method == 'POST':
        email = str(request.POST.get('email')).strip()
        fname = str(request.POST.get('fname')).strip()
        lname = str(request.POST.get('lname')).strip()
        pass1 = request.POST.get('password')
        pass2 = request.POST.get('confirm-password')

        signup_context['currEmail'] = email
        signup_context['currFname'] = fname
        signup_context['currLname'] = lname

        if User.objects.filter(email=email).exists() or User.objects.filter(username=email):
            signup_context['emailExist'] = True
            

            return render(request, "authentication/signup.html", signup_context)

        if pass1 != pass2:
            signup_context['passError'] = True
            signup_context['passErrorMessage'] = "Password doesn't match!"
            return render(request, "authentication/signup.html", signup_context)

        if not validatePassword(pass1):
            signup_context['passError'] = True
            signup_context['passErrorMessage'] = 'Enter a valid password!'
            return render(request, "authentication/signup.html", signup_context)

            

        newUser = User.objects.create_user(email, email, pass1)
        newUser.first_name = fname
        newUser.last_name = fname
        newUser.is_active = True
        newUser.save()
        if newUser is not None:
            login(request, newUser)
            return redirect('home')
    return render(request, "authentication/signup.html", signup_context)


def signin(request):
    login_context = {}
    if request.method == 'POST':
        email = str(request.POST.get('email')).strip()
        pass1 = request.POST.get('password')

        user = authenticate(username=email, password=pass1)

        if user is not None:
            login(request, user)
            return redirect('home')

    if request.user.is_authenticated:
        return redirect('home')

    return render(request, 'authentication/login.html', login_context)


def signout(request):
    logout(request)
    return redirect('home')


# helper functions

def validatePassword(password):
    return True if re.match(PASS_REGEX, password) else False

foods/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.urls import reverse_lazy
from django.contrib.auth.models import User
from .models import Recipe
from .forms import RecipeForm
# Create your views here.
def home(request):
    return render(request, "foods/home.html")


class RecipesListView(ListView):
    model = Recipe
    template_name = 'foods/recipes_list_view.html'
    context_object_name = 'recipes'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        search_input = self.request.GET.get('search-input') or ''

        if search_input:
            context['recipes'] = context['recipes'].filter(title__icontains=search_input)
        context['search_input_text'] = search_input

        return context


class RecipesDetailView(DetailView):
    model = Recipe
    template_name = 'foods/recipe_detail_view.html'
    context_object_name = 'recipe_detail'
    pk_url_kwarg = 'pk'


class UserRecipesListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'foods/user_recipes_list_view.html'
    context_object_name = 'user_recipes'

    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_recipes'] = context['user_recipes'].filter(user=self.request.user)

        return context

class RecipesCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'foods/recipe_create_view.html'
    success_url = reverse_lazy('my-recipes')

    def form_valid(self, form):
        form = RecipeForm(self.request.POST, self.request.FILES)
        form.instance.user = self.request.user
        
        return super().form_valid(form)



class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'foods/recipe_create_view.html'
    success_url = reverse_lazy('my-recipes')

    def form_valid(self, form):
        form = RecipeForm(self.request.POST, self.request.FILES)
        form.instance.user = self.request.user
        
        return super().form_valid(form)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'foods/recipe_delete_view.html'
    success_url = reverse_lazy('my-recipes')

    def get_queryset(self):
        owner = self.request.user
        return self.model.objects.filter(user=owner)

authentication/templates/authentication/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'authentication/style.css' %}">
    <title>FRF - Food Recipe Finder</title>
</head>

<body>
    <div class="navbar container">
        <div class="logo">
            <div class="circle"></div>
            <h3>FRF</h3>
        </div>
    </div>

    <div class="container body">
        <div class="heading">
            <h1>Welcome to <span>FRF</span></h1>
            <!-- <p>Find any foods you like!</p> -->
        </div>
        <div class="forms">
            <div class="image">
                <img src="{% static 'foods/images/login-sign.jpg' %}" alt="">
            </div>
            <div class="signup">
                <div class="heading">
                    <h1>
                    {% block reg_name %}
                        Sign Up
                    {% endblock reg_name %}
                        </h1>
                </div>
                <div class="form">
                    
                    {% block form %}
                                            
                    
                    {% endblock form %}

                </div>
            </div>
        </div>
    </div>
    
    {% block script %}
        <script></script>
    {% endblock script %}
        
</body>

</html>

authentication/templates/authentication/login.html
{% extends 'authentication/base.html' %}
{% load static %}


{% block reg_name %}
    Login
{% endblock reg_name %}
    

{% block form %}

{% if not user.is_authenticated %}
<form action="/login" method="post">
    {% csrf_token %}
    <div class="input">
        <input type="email" required name="email">
        <span>Email</span>
    </div>
    <div class="input">
        <input type="password" required name="password">
        <span>Password</span>
    </div>
       
    <p class="already">Don't have an account? <a href="{% url 'sign-up' %}">Signup</a></p>
    <input type="submit" value="Login">
</form>
{% endif %}
    


{% endblock form %}

authentication/templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load static %}


{% block reg_name %}
Sign Up
{% endblock reg_name %}


{% block form %}

<form action="/sign-up" method="post" onsubmit="validateForm(event)" id="form">
    {% csrf_token %}
    <div class="input" id="fname-div">
        <input type="text" required name="fname" id="fname" value="{{ currFname }}">
        <span>First Name</span>
        <small class="hidden">Please use alphabets!</small>
    </div>

    <div class="input" id="lname-div">
        <input type="text" required name="lname" id="lname" value="{{ currLname }}">
        <span>Last Name</span>
        <small class="hidden">Please use alphabets!</small>
    </div>

    {% if emailExist %}
    <div class="input error" id="email-div">
        {% else %}
        <div class="input" id="email-div">
            {% endif %}
            <input type="email" required name="email" id="email" value="{{ currEmail }}">
            <span>Email</span>
            <small class="hidden">Email already exists!</small>
        </div>


        {% if passError %}
            <div class="input error" id="password-div">
        {% else %}
            <div class="input" id="password-div">
        {% endif %}

                <input type="password" required name="password" id="password">
                <span>Password</span>
                <small class="hidden">{{ passErrorMessage }}</small>

                <div class="pass_msg pass_msg_hidden">
                    <b> Password requirements:</b>
                    <ul>

                        <li>8 or more characters</li>
                        <li>Atleast one capital letter</li>
                        <li>One number[0-9]</li>
                        <li>One special character (@,^&:% etc.)</li>

                    </ul>
                </div>
            </div>
            <div class="input" id="confirm-password-div">
                <input type="password" required name="confirm-password" id="confirm-password">
                <span>Confirm Password</span>
                <small class="hidden">Error message goes here</small>
            </div>
            <p class="already">Already have an account? <a href="{% url 'sign-in' %}">Login</a></p>
            <input type="submit" value="SignUp">
</form>

{% endblock form %}


{% block script %}
<script src="{% static 'authentication/script.js' %}"></script>
{% endblock script %}

foods/templates/foods/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block css %}
        
    {% endblock css %}
        
    <link rel="stylesheet" href="{% static 'foods/style.css' %}">
    <title>FRF - Food Recipe Finder</title>
</head>

<body>
    <div class="navbar container">
        <div class="logo">
            <div class="circle"></div>
            <h3>FRF</h3>
        </div>
        <div class="links">
            
            {% if user.is_authenticated %}
                
                {% block recipe_link %}
                <a href="{% url 'my-recipes' %}">My Recipes</a>
                {% endblock recipe_link %}
                    
                <a href="{% url 'sign-out' %}" class="signup-btn logout">Logout</a>
            {% else %}
                    
            <a href="{% url 'sign-in' %}">Login</a>
            <a href="{% url 'sign-up' %}" class="signup-btn">Sign Up</a>
            {% endif %}
            
        </div>
    </div>

    <div class="container body">
        
        {% block body %}
            blockname
        {% endblock body %}
            
        

    </div>
    
    {% block script %}
        
    {% endblock script %}
    <script src="https://kit.fontawesome.com/e97fbec914.js" crossorigin="anonymous"></script>
</body>

</html>

foods/templates/foods/home.html
{% extends 'foods/base.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'foods/home.css' %}">
    
{% endblock css %}
    

<!-- {% block recipe_link %}
<a href="{% url 'home' %}">Home</a>
    
{% endblock recipe_link %} -->
    

{% block body %}
<div class="home">
    <div class="left">
        <i class="fa-solid fa-mug-hot"></i>
        <h1>Welcome to <br> <span>FRF</span></h1>
        <p>Find the recipes of food you like!</p>
        <div class="btn">
        <a href="{% url 'create-recipe' %}">Submit Recipes</a>
        <a href="{% url 'recipes' %}">Find Recipes</a>
    </div>
    </div>
    <div class="right">
        <img src="{% static 'foods/images/bg_img.jpg' %}" alt="">
    </div>
    </div>
{% endblock body %}
    

foods/templates/foods/recipe_create_view.html
{% extends 'foods/base.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'foods/recipe_create.css' %}">
{% endblock css %}

{% block body %}
<div class="create-form">
    <a href="{% url 'my-recipes' %}"><i class="fa-solid fa-arrow-left"></i> Go Back</a>

    <h1>Submit your recipe!</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-items">
            {% for field in form %}
            <div class="form-item">
                {{ field.label }}
                {{ field }}
            </div>
            {% endfor %}
           
        </div>
        <div class="sub-btn">
        <input type="submit" value="Submit Recipe">
    </div>

    </form>
</div>

{% endblock body %}

foods/templates/foods/recipe_delete_view.html
{% extends 'foods/base.html' %}
{% load static %}



{% block css %}
<link rel="stylesheet" href="{% static 'foods/recipe_list.css' %}">
<style>
    #delete  {
        background-color: #e8594f;
        padding: 5px 10px;
        font-family: 'Poppins', serif;
        font-size: 16px;
        border-radius: 2px;
        cursor: pointer;
    }
    .links-delete {
        margin-top: 10px;
    }
    .links-delete a {
        margin-left: 10px;
        color: var(--dark-color);
    }
    .links-delete a:hover {
        color: var(--green-color);
    }

    #delete:hover  {
        background-color: #e50d2f;
    }


</style>
    
{% endblock css %}
    
{% block recipe_link %}
<a href="{% url 'home' %}">Home</a>

{% endblock recipe_link %}


{% block body %}
<div class="view">
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete this Recipe? <b>{{ recipe.title }}</b></p>
        <div class="links-delete">
        <input type="submit" value="Delete" id="delete">
        
        <a href="{% url 'my-recipes' %}">Cancel</a>
        
            
    </div>
    </form>
</div>
        
        

{% endblock body %}

foods/templates/foods/recipe_detail_view.html
{% extends 'foods/base.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'foods/recipe_detail.css' %}">
    
{% endblock css %}
    

{% block body %}
    <div class="view">
        <div class="detail">
            <a href="{% url 'recipes' %}"><i class="fa-solid fa-arrow-left"></i> Go Back</a>
            <div class="heading">
                <h1>{{ recipe_detail.title }}</h1>
                
                {% if user.is_authenticated %}
                    {% if user.id == recipe_detail.user.id %}
                    <div class="links">
                    
                        <a href="{% url 'recipes-edit' recipe_detail.id %}"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a href="{% url 'recipes-delete' recipe_detail.id %}"><i class="fa-solid fa-trash-can"></i></a>
                    </div>
                    {% endif %}
        
                {% endif %}
                    
                
        </div>
            <p>by <span>{{ recipe_detail.user.first_name }}</span></p>
            <div class="explanation">
                <h3>Ingredients</h3>
                <p>{{ recipe_detail.ingredients }}</p>
        
                <h3 class="prepare">How to Prepare</h3>
                <p>{{ recipe_detail.description }}</p>
            </div>

        </div>
        <div class="image">
            <img src="{{ recipe_detail.pic_file.url }}" alt="{{ recipe_detail.title }}.jpg">
        </div>
    </div>
{% endblock body %}
    

foods/templates/foods/recipes_list_view.html
{% extends 'foods/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'foods/recipe_list.css' %}">
{% endblock css %}

{% block body %}
<div class="view">
<div class="heading">
    <h1>Welcome to <span>FRF</span></h1>
    <p>Find any foods you like!</p>
</div>
<div class="form">
<div id="cover">
    <form method="get" action="">
      <div class="tb">
        <div class="td"><input type="text" placeholder="Search" name="search-input" value="{{ search_input_text }}"></div>
        <div class="td" id="s-cover">
          <button type="submit">
            <div id="s-circle"></div>
            <span></span>
          </button>
        </div>
      </div>
    </form>
  </div>
</div>

<div class="recipes">

   

    <section class="dl-blurbs">
        <dl>

            {% for recipe in recipes %}

            {% if forloop.counter0|divisibleby:"2" %}
            <a href="{% url 'recipes-detail' recipe.id %}">
                <dt>{{ recipe.title }}</dt>
                <dd>by <span>{{ recipe.user }}</span></dd>
            </a>
            {% endif %}

            {% endfor %}
        </dl>
        <dl>

            {% for recipe in recipes %}

            {% if not forloop.counter0|divisibleby:"2" %}
            <a href="{% url 'recipes-detail' recipe.id %}" class="recipe-btn">
                <dt>{{ recipe.title }}</dt>
                <dd>by <span>{{ recipe.user }}</span></dd>

            </a>
            {% endif %}

            {% endfor %}
        </dl>
    </section>





</div>
</div>
{% endblock body %}

foods/templates/foods/user_recipes_list_view.html
{% extends 'foods/base.html' %}
{% load static %}



{% block css %}
<link rel="stylesheet" href="{% static 'foods/recipe_list.css' %}">
    
{% endblock css %}
    
{% block recipe_link %}
<a href="{% url 'home' %}">Home</a>

{% endblock recipe_link %}


{% block body %}
<div class="view">
    
    <div class="recipes">

        <div class="heading" style="text-align: left; align-items: center; margin-bottom: 25px; display: flex;
        justify-content: space-between; flex-direction: row;">
            <h1>Hello,<span style="color: var(--green-color); text-transform: capitalize;">{{ user.first_name }}</span></h1>
            <a href="{% url 'create-recipe' %}" class="add-recipe">Add Recipe</a>
        </div>
        
        {% if user_recipes|length > 0 %}
        <section class="dl-blurbs">
            <dl>

                {% for recipe in user_recipes %}

                {% if forloop.counter0|divisibleby:"2" %}
                <a href="{% url 'recipes-detail' recipe.id %}">
                    <dt>{{ recipe.title }}</dt>
                    <dd>by <span>{{ recipe.user }}</span></dd>

                </a>
                <div class="links">
                    <a href="{% url 'recipes-delete' recipe.id %}"><i class="fa-solid fa-trash-can"></i></a>
                    <a href="{% url 'recipes-edit' recipe.id %}"><i class="fa-solid fa-pen-to-square"></i></a>
            </div>
                {% endif %}

                {% endfor %}
            </dl>
            <dl>

                {% for recipe in user_recipes %}

                {% if not forloop.counter0|divisibleby:"2" %}
                <a href="{% url 'recipes-detail' recipe.id %}" class="recipe-btn">
                    <dt>{{ recipe.title }}</dt>
                    <dd>by <span>{{ recipe.user }}</span></dd>

                </a>
                <div class="links">
                    <a href="{% url 'recipes-delete' recipe.id %}"><i class="fa-solid fa-trash-can"></i></a>
                    <a href="{% url 'recipes-edit' recipe.id %}"><i class="fa-solid fa-pen-to-square"></i></a>
            </div>
                {% endif %}

                {% endfor %}
            </dl>
        </section>

        {% else %}
            <div class="nodata">
                No recipes yet! Add some <a href="" style="color: blue;">here.</a>
            </div>
        {% endif %}
            
       





    </div>
</div>

{% endblock body %}